/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF OBJECT_ID('[dbo].[vw_Employee_Data]') IS NOT NULL
	DROP VIEW [dbo].[vw_Employee_Data];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE    VIEW [dbo].[vw_Employee_Data]
 AS 
  

 SELECT E.BusinessEntityID ,E.Rate,E.PayFrequency,E.Rate*E.PayFrequency AS Salary,
 F.JobTitle , H.[Name]  AS Department FROM  HumanResources.EmployeePayHistory E
JOIN HumanResources.Employee F ON E.BusinessEntityID = F.BusinessEntityID
JOIN HumanResources.EmployeeDepartmentHistory G ON F.BusinessEntityID = G.BusinessEntityID
JOIN  HumanResources.Department H ON G.DepartmentID = H.DepartmentID 
  
GO
