/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF OBJECT_ID('[dbo].[UDF_ADD]') IS NOT NULL
	DROP FUNCTION [dbo].[UDF_ADD];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[UDF_ADD] (@A INT,  @B INT)
 RETURNS INT 
 AS 
  BEGIN 
       DECLARE @c INT    
       SET @c = @a + @B
       RETURN  @c
    END 
GO
