/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF OBJECT_ID('[dbo].[UDF_TABLE]') IS NOT NULL
	DROP FUNCTION [dbo].[UDF_TABLE];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
  CREATE    FUNCTION [dbo].[UDF_TABLE] (@VAL  INT )
    RETURNS TABLE
	 AS
		RETURN   
		 (SELECT * FROM Employees WHERE emp_id = @VAL)  
GO
