/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dbo].[AccountNumber]') IS NOT NULL
	DROP TYPE [dbo].[AccountNumber];

GO
CREATE TYPE [dbo].[AccountNumber] FROM nvarchar (15) NULL
GO
