/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dbo].[Name]') IS NOT NULL
	DROP TYPE [dbo].[Name];

GO
CREATE TYPE [dbo].[Name] FROM nvarchar (50) NULL
GO
