/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Employees]
(
[emp_id] [int] NOT NULL,
[LastName] [varchar] (50) NULL,
[FirstName] [varchar] (50) NULL,
[OccupationID] [int] NULL,
[OccupationTitle] [varchar] (50) NULL
)
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_EMPLOYEE]  ON [dbo].[Employees]
  INSTEAD OF  INSERT, DELETE
  AS 
  BEGIN 
   PRINT 'THE INSTEAD TRIGGER START'
  END 
GO
