/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Employees_Distnation]
(
[emp_id] [int] NOT NULL,
[LastName] [varchar] (50) NULL,
[FirstName] [varchar] (50) NULL,
[OccupationID] [int] NULL,
[OccupationTitle] [varchar] (50) NULL,
[is_deleted] [bit] NOT NULL CONSTRAINT [DF__Employees__is_de__6A1BB7B0] DEFAULT ((0))
)
GO
