/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ExportColumnDemo]
(
[ProductID] [int] NULL,
[ProductName] [nvarchar] (50) NULL,
[Description] [nvarchar] (50) NULL,
[FilePath] [nvarchar] (255) NULL
)
GO
