/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[MyUsers]
(
[UserName] [nvarchar] (50) NULL,
[Password] [nvarchar] (50) NULL,
[Country] [nvarchar] (50) NULL,
[Email] [nvarchar] (50) NULL
)
GO
