/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Occupation]
(
[OccupationID] [smallint] NOT NULL IDENTITY(1, 1),
[OccupationTitle] [varchar] (50) NOT NULL
)
GO
ALTER TABLE [dbo].[Occupation] ADD CONSTRAINT [PK_Occupation_OccupationID] PRIMARY KEY CLUSTERED ([OccupationID])
GO
