/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OLE DB Destination]
(
[ProductID] [int] NULL,
[ProductName] [varchar] (50) NULL,
[isDeleted] [int] NULL CONSTRAINT [df_isdelete] DEFAULT ((0))
)
GO
