/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[OurIFTest]
(
[Col1] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[OurIFTest] ADD CONSTRAINT [PK__OurIFTes__A259EE5466419404] PRIMARY KEY CLUSTERED ([Col1])
GO
