/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[TermExtractionDemo]
(
[Term] [nvarchar] (150) NULL,
[Score] [int] NULL
)
GO
